import { LevelConfig } from './types';

export const COL_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'] as const;
export const ROW_NUMBERS = Array.from({ length: 15 }, (_, i) => 15 - i); // 15 down to 1

export function formatCoord(row: number, col: number): string {
  const colLetter = COL_LETTERS[col] || '?';
  const rowNumber = 15 - row;
  return `${colLetter}${rowNumber}`;
}

export const STAR_POINTS: [number, number][] = [
  [3, 3],
  [3, 11],
  [7, 7],
  [11, 3],
  [11, 11],
];

// Hệ thống cấp độ AI thăng tiến theo số trận thắng (Mỗi level cần 3 ván thắng)
export const AI_LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Beginner',
    vietnameseName: 'Vỡ Lòng',
    tag: 'Cực Dễ Thắng',
    minWins: 0,
    maxWins: 2,
    depth: 1,
    candidateCount: 5,
    threatVision: 0.40,    // Nhận biết 40% đe dọa trực diện (hay lơ đễnh để hở nước 4)
    attackWeight: 1.0,
    defenseWeight: 0.25,   // Ít khi phòng thủ gắt gao, nhường thế trận tấn công cho bạn
    temperature: 0.85,     // Chọn nước đi phân phối xác suất mềm mại, rất dễ chơi
    vcfDepth: 0,
    vctDepth: 0,
    color: '#10b981',
    gradient: 'from-emerald-400 to-teal-500',
    badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    avatar: 'eye_roll',
    description: 'Mới tập làm quen bàn cờ, hay lơ đễnh bỏ sót nước và ít khi phòng thủ gắt gao.',
    tactics: 'Thường xuyên để lộ sơ hở lớn cho bạn thỏa sức kết liễu.',
  },
  {
    id: 2,
    name: 'Rookie',
    vietnameseName: 'Tân Thủ',
    tag: 'Dễ Tiếp Cận',
    minWins: 3,
    maxWins: 5,
    depth: 1,
    candidateCount: 6,
    threatVision: 0.65,    // Tăng nhẹ sự tập trung (nhận biết 65% hiểm họa trực diện)
    attackWeight: 1.0,
    defenseWeight: 0.45,   // Bắt đầu chú ý phòng thủ hơn một chút nhưng vẫn dễ chịu
    temperature: 0.60,     // Độ ngẫu nhiên giảm nhẹ, đánh chắc hơn Level 1
    vcfDepth: 0,
    vctDepth: 0,
    color: '#14b8a6',
    gradient: 'from-teal-500 to-cyan-500',
    badgeBg: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    avatar: 'eye_roll',
    description: 'Đã làm quen thế trận, bắt đầu chú ý các nước cờ nguy hiểm nhưng vẫn còn nhiều sơ hở.',
    tactics: 'Đòn đánh đơn giản, đôi khi để lọt đòn tấn công của bạn.',
  },
  {
    id: 3,
    name: 'Novice',
    vietnameseName: 'Tập Sự',
    tag: 'Chắc Tay Hơn',
    minWins: 6,
    maxWins: 8,
    depth: 1,
    candidateCount: 8,
    threatVision: 0.85,
    attackWeight: 1.0,
    defenseWeight: 0.70,
    temperature: 0.35,
    vcfDepth: 0,
    vctDepth: 0,
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-500',
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    avatar: 'eye_roll',
    description: 'Nắm vững luật cơ bản, ưu tiên tấn công và phòng ngự trực diện, lối đánh phóng khoáng.',
    tactics: 'Đòn đánh cơ bản, hạn chế sai sót thô sơ.',
  },
  {
    id: 4,
    name: 'Casual',
    vietnameseName: 'Nghiệp Dư',
    tag: 'Cảnh Giác Cao',
    minWins: 9,
    maxWins: 11,
    depth: 2,
    candidateCount: 10,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 0.95,
    temperature: 0.15,
    vcfDepth: 0,
    vctDepth: 0,
    color: '#3b82f6',
    gradient: 'from-sky-500 to-blue-600',
    badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
    avatar: 'eye_roll',
    description: 'Biết phán đoán nước cờ tiếp theo, chủ động phong tỏa các thế 3 mở của bạn.',
    tactics: 'Phòng thủ cảnh giác, hạn chế sơ hở.',
  },
  {
    id: 5,
    name: 'Semi-Pro',
    vietnameseName: 'Bán Chuyên',
    tag: 'Phản Xạ Nhanh',
    minWins: 12,
    maxWins: 14,
    depth: 2,
    candidateCount: 12,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.05,
    temperature: 0.08,
    vcfDepth: 2,
    vctDepth: 0,
    color: '#6366f1',
    gradient: 'from-blue-500 to-indigo-600',
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    avatar: 'eye_roll',
    description: 'Tấn công dứt khoát, bắt đầu biết chớp thời cơ kết liễu bằng chuỗi nước 4 cự ly ngắn.',
    tactics: 'Sát cục chớp nhoáng khi đối thủ sơ hở.',
  },
  {
    id: 6,
    name: 'Adept',
    vietnameseName: 'Cao Thủ',
    tag: 'Gài Bẫy Khéo Léo',
    minWins: 15,
    maxWins: 17,
    depth: 3,
    candidateCount: 14,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.15,
    temperature: 0.03,
    vcfDepth: 4,
    vctDepth: 2,
    color: '#8b5cf6',
    gradient: 'from-indigo-500 to-purple-600',
    badgeBg: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    avatar: 'eye_roll',
    description: 'Tính trước nhiều nước đi, biết gài các thế đôi 3-3, 4-3 hiểm hóc để giành thế chủ động.',
    tactics: 'Gài bẫy tấn công chủ động bằng đòn bẫy đôi.',
  },
  {
    id: 7,
    name: 'Expert',
    vietnameseName: 'Danh Thủ',
    tag: 'Đòn Đánh Đa Dạng',
    minWins: 18,
    maxWins: 20,
    depth: 4,
    candidateCount: 15,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.20,
    temperature: 0.0,
    vcfDepth: 6,
    vctDepth: 4,
    color: '#a855f7',
    gradient: 'from-purple-500 to-fuchsia-600',
    badgeBg: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/40',
    avatar: 'eye_roll',
    description: 'Kết hợp nhuần nhuyễn giữa nước 3 mở và ép nước 4 liên tục tạo thế bẫy không lối thoát.',
    tactics: 'Phối hợp đòn đe dọa VCT trung cuộc sắc bén.',
  },
  {
    id: 8,
    name: 'Master',
    vietnameseName: 'Kiện Tướng',
    tag: 'Phòng Thủ & Phản Công',
    minWins: 21,
    maxWins: 23,
    depth: 4,
    candidateCount: 16,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.25,
    temperature: 0.0,
    vcfDepth: 8,
    vctDepth: 4,
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    avatar: 'eye_roll',
    description: 'Kỹ năng toàn diện, nhìn thấu các đòn bẫy từ xa, chuyển đổi phòng thủ sang phản công sắc bén.',
    tactics: 'Phòng ngự phản công chuẩn xác, chuyển hóa thế trận nhanh chóng.',
  },
  {
    id: 9,
    name: 'Grandmaster',
    vietnameseName: 'Đại Kiện Tướng',
    tag: 'Bao Quát Toàn Cục',
    minWins: 24,
    maxWins: 26,
    depth: 5,
    candidateCount: 18,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.28,
    temperature: 0.0,
    vcfDepth: 12,
    vctDepth: 6,
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
    badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    avatar: 'eye_roll',
    description: 'Bao quát toàn bộ bàn cờ, khống chế các điểm giao thoa chiến lược, thế trận chặt chẽ.',
    tactics: 'Chiến thuật bao quát toàn cục và sát cục tầm xa.',
  },
  {
    id: 10,
    name: 'Supreme Legend',
    vietnameseName: 'Kỳ Thánh',
    tag: 'Sát Cục Tầm Xa',
    minWins: 27,
    maxWins: 29,
    depth: 5,
    candidateCount: 18,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.30,
    temperature: 0.0,
    vcfDepth: 16,
    vctDepth: 8,
    color: '#7c3aed',
    gradient: 'from-violet-600 to-indigo-700',
    badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
    avatar: 'eye_roll',
    description: 'Bậc thầy chiến thuật trung cuộc, nhìn thấu mọi đường công thủ và dứt điểm bằng đòn bẫy tầm xa.',
    tactics: 'Sát cục tầm xa, bẻ gãy mọi hướng tấn công của đối thủ.',
  },
  {
    id: 11,
    name: 'Abyssal Demon',
    vietnameseName: 'Vô Cực Ma Vương',
    tag: 'Áp Đảo Tuyệt Đối',
    minWins: 30,
    maxWins: 32,
    depth: 6,
    candidateCount: 20,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.30,
    temperature: 0.0,
    vcfDepth: 20,
    vctDepth: 10,
    color: '#dc2626',
    gradient: 'from-red-600 to-rose-800',
    badgeBg: 'bg-red-600/20 text-red-300 border-red-600/40',
    avatar: 'eye_roll',
    description: 'Lối đánh hung hãn tàn khốc, liên tục tung đòn bẫy ép đối phương nghẹt thở vào tử địa.',
    tactics: 'Đòn bẫy liên hoàn vô tận, ép nghẹt thế cờ đối phương.',
  },
  {
    id: 12,
    name: 'Unbeatable God',
    vietnameseName: 'Thần Cờ (Bất Khả Chiến Bại)',
    tag: 'Hoàn Hảo Tuyệt Đối',
    minWins: 33,
    maxWins: 9999,
    depth: 6,
    candidateCount: 20,
    threatVision: 1.0,
    attackWeight: 1.0,
    defenseWeight: 1.30,
    temperature: 0.0,
    vcfDepth: 26,
    vctDepth: 14,
    color: '#ef4444',
    gradient: 'from-red-500 via-rose-600 to-purple-700',
    badgeBg: 'bg-red-500/20 text-red-300 border-red-500/40 shadow-lg shadow-red-500/20',
    avatar: 'eye_roll',
    description: 'Tính toán chuẩn xác không sơ hở, phát hiện chuỗi kết liễu trận đấu VCF/VCT từ cự ly vô hạn.',
    tactics: 'Tuyệt đối không có sơ hở, tính toán hoàn hảo mọi nhánh cờ.',
  },
];

export function getLevelConfigByWins(wins: number, manualLevel: number | null = null): LevelConfig {
  if (manualLevel !== null && manualLevel >= 1 && manualLevel <= AI_LEVELS.length) {
    return AI_LEVELS[manualLevel - 1];
  }
  for (const lvl of AI_LEVELS) {
    if (wins >= lvl.minWins && wins <= lvl.maxWins) {
      return lvl;
    }
  }
  return AI_LEVELS[AI_LEVELS.length - 1];
}

// Điểm đánh giá các hình thái thế cờ Gomoku
export const SCORES = {
  FIVE: 10000000,          // 5 liên tiếp (thắng ngay)
  OPEN_FOUR: 1000000,      // 4 mở 2 đầu (chắc chắn thắng ở nước kế)
  BLOCKED_FOUR: 100000,    // 4 chặn 1 đầu (bắt buộc phải đỡ)
  OPEN_THREE: 100000,      // 3 mở 2 đầu (hiểm họa lớn, chuẩn bị thành 4 mở)
  BLOCKED_THREE: 10000,    // 3 chặn 1 đầu
  OPEN_TWO: 10000,         // 2 mở 2 đầu
  BLOCKED_TWO: 1000,       // 2 chặn 1 đầu
  SINGLE: 100,             // 1 quân đơn lẻ
};
