import { UserStats } from '../src/game/types';

/**
 * Factory tạo đối tượng UserStats chuẩn cho môi trường kiểm thử
 */
export const createTestStats = (overrides: Partial<UserStats> = {}): UserStats => ({
  campaign: {
    wins: 0,
    losses: 0,
    draws: 0,
    currentStreak: 0,
    bestStreak: 0,
    totalGames: 0,
    ...(overrides.campaign || {}),
  },
  puzzle: {
    currentLevel: 1,
    totalSolved: 0,
    totalFailed: 0,
    currentStreak: 0,
    bestStreak: 0,
    totalGames: 0,
    solvedByStars: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
    ...(overrides.puzzle || {}),
  },
  custom: {
    wins: 0,
    losses: 0,
    draws: 0,
    currentStreak: 0,
    bestStreak: 0,
    totalGames: 0,
    byBotLevel: {},
    ...(overrides.custom || {}),
  },
  blitz: {
    currentLevel: 1,
    highestLevel: 1,
    totalWins: 0,
    totalLosses: 0,
    timeoutLosses: 0,
    bestStreak: 0,
    currentStreak: 0,
    totalGames: 0,
    selectedTimeSeconds: 10,
    ...(overrides.blitz || {}),
  },
  tutor: {
    currentLevel: 1,
    highestLevel: 1,
    totalWins: 0,
    totalLosses: 0,
    currentStreak: 0,
    bestStreak: 0,
    totalGames: 0,
    byBotLevel: {},
    ...(overrides.tutor || {}),
  },
  guide: {
    completedLessons: [],
    unlockedChapters: [1],
    sandboxPresetLoadedCount: 0,
    totalLessonsCompleted: 0,
    lastSelectedLessonId: 'lesson_1_1',
    ...(overrides.guide || {}),
  },
  wins: overrides.wins ?? 0,
  losses: overrides.losses ?? 0,
  draws: overrides.draws ?? 0,
  currentStreak: overrides.currentStreak ?? 0,
  bestStreak: overrides.bestStreak ?? 0,
  totalGames: overrides.totalGames ?? 0,
  manualLevel: overrides.manualLevel ?? null,
});
