export const PUZZLE_TITLES: Record<number, string[]> = {
  1: [
    'Nhất Kích Tất Sát',
    'Phi Long Tại Thiên',
    'Đoạn Kim Quyết',
    'Đoạt Mệnh Trực Tung',
    'Tà Phong Trảm',
    'Bạch Hổ Xuất Sơn',
    'Lôi Đình Vạn Quân',
    'Nhất Dương Chỉ',
    'Khai Sơn Phá Thạch',
    'Hám Sơn Trảm',
    'Xuyên Tâm Tiễn',
    'Lạc Diệp Vô Ngân',
  ],
  2: [
    'Song Long Hí Châu',
    'Song Kiếm Hợp Bích',
    'Song Đao Đoạt Mệnh',
    'Lưỡng Nghi Phân Định',
    'Âm Dương Hợp Nhất',
    'Gọng Kìm Chữ V',
    'Giao Tiễn Đoạt Hồn',
    'Long Hổ Tương Tranh',
    'Nhạn Quá Hàn Đàm',
    'Bình Sa Lạc Nhạn',
    'Huyền Vũ Thổ Nạp',
    'Kim Quy Phục Ba',
  ],
  3: [
    'Tam Tinh Tụ Đỉnh',
    'Tam Tiên Quy Đạo',
    'Tam Thể Hợp Nhất',
    'Tam Long Xuất Hải',
    'Tam Tuyệt Kiếm Trận',
    'Tam Xoa Kích',
    'Tam Giác Trận Đồ',
    'Cửu Cung Ba Hướng',
    'Thiên Cương Bắc Đẩu',
    'Bách Bộ Xuyên Dương',
    'Phong Quyển Tàn Vân',
    'Độc Cô Khai Môn',
  ],
  4: [
    'Tứ Linh Quy Vị',
    'Tứ Phương Thần Trận',
    'Tứ Kiếm Tru Tiên',
    'Tứ Cực Hợp Kích',
    'Tứ Trận Hợp Long',
    'Tứ Hải Giao Phong',
    'Thiên La Địa Võng',
    'Long Môn Phi Kiếm',
    'Bát Môn Kim Tỏa',
    'Kim Chung Tráo Môn',
    'Vạn Mã Bôn Đằng',
    'Hàn Băng Thần Chưởng',
  ],
  5: [
    'Ngũ Long Tuyệt Sát',
    'Ngũ Tinh Liên Châu',
    'Ngũ Thần Tụ Hội',
    'Ngũ Hành Bát Quái',
    'Ngũ Hổ Vồ Mồi',
    'Ngũ Lôi Oanh Đỉnh',
    'Bát Trận Đồ',
    'Thập Diện Mai Phục',
    'Vạn Kiếm Quy Tông',
    'Càn Khôn Đại Na Di',
    'Hỏa Thiêu Xích Bích',
    'Long Đằng Hổ Hạc',
  ],
  6: [
    'Lục Kiếm Trảm Tiên',
    'Lục Đạo Luân Hồi',
    'Lục Tinh Thần Trận',
    'Lục Trận Hợp Kích',
    'Lục Hợp Bát Hoang',
    'Lục Tuyệt Thần Công',
    'Bá Vương Cử Đỉnh',
    'Thiên Ngoại Phi Tiên',
    'Cửu Tiêu Lạc Lôi',
    'Vô Ngã Vô Tướng',
    'Độc Cô Cửu Kiếm',
    'Phong Lôi Tuyệt Ảnh',
  ],
  7: [
    'Thất Tinh Bắc Đẩu',
    'Thất Long Quy Tụ',
    'Thất Kiếm Trảm Yêu',
    'Thất Sát Phá Quân',
    'Thất Trảm Vô Song',
    'Thất Tuyệt Trận Đồ',
    'Cửu Long Tranh Bá',
    'Thần Long Đoạt Mệnh',
    'Thiên Ma Giáng Thế',
    'Cực Ý Vô Cực',
    'Vô Cực Sát Trận',
    'Đăng Phong Tạo Cực',
  ],
};
